### ISSUE TITLE
allow default config to resolve handover to Ethererum

### ISSUE THREAD

**Issue by linux-leo** [anothersoft/hns-bridge#2]
I am mainly asking this to allow hns.is to resolve .forever and .badass subdomains as well as any .eth domain.

These two dns servers should work:

54.144.153.187
52.5.129.119

**Comment by linux-leo** [comment]
Heres an explanation as to why this is necessary, and a link to the article from where i got the nameservers:

https://foreverdomains.io/about/index.html
https://ca98am79.medium.com/introducing-badass-domains-4d90bd48108b

**Comment by angrymouse** [comment]
Sorry for late reply. We use own DNS servers, we run HNSD node and use it. We don't trust third-party DNS servers
